### ISSUE TITLE
ds1302 cant set the time

### ISSUE THREAD

**Issue by ZeinSleiman** [Martin-HiPi/HiPi-Project-kit#3]
Fairly new to Raspberry PI, sensors and Python so I dont know if this is a real issue or not. 

To reproduce:

1. Connected my Raspberry PI 2 Model B to the RTC DS1302 following the manual. 
2. Opened the program and ran it. (The RTC has a blue light to indicate it is connected)

I get an error that the Hours must have a value between 0 and 23 on line 229 of ds1302.py. When I checked the actual value was 80.

I tried to reset the value but nothing happened. I checked the check_sanity(self) code and it is always returning false because the year is 2000. When I comment out the check_sanity() call, the value is set and everything is working fine after that.

Please let me know if I didnt provide enough information or if this is a normal behavior.

**Comment by realizator** [comment]
Hi @ZeinSleiman,
One question: is your RPi connected to the Internet and able to get the actual time?

**Comment by ZeinSleiman** [comment]
Ah! It is not connected to the internet. So it must be connected to get the right value? I can try it later today.

**Comment by realizator** [comment]
Without the Internet, the system will set something like 01 of January 2000. And this date does not pass the sanity check.
If you have no internet access from your Pi, you can try to set the time by using raspi-config, or use a terminal command like this one:

`sudo date -s '2021-27-07 15:30:00'` 
([source link to RPF forum](https://www.raspberrypi.org/forums/viewtopic.php?t=182089))

**Comment by ZeinSleiman** [comment]
Awesome thanks a lot.
